

BINDIR = ../../../bin

markup:
	$(BINDIR)/makeclasslink -p "RQ" ravel.pmx > ravel-markup.pmx

svg:
	$(BINDIR)/score2svg ravel-markup.pmx > ravel-markup-svg.html

html:
	$(BINDIR)/makeclasslink -h -p "RQ" ravel.pmx > ravel-markup.html





